# version : "3.3"
# services :
#   web :
#      image: "yashkapadi175/notes-app:latest"
#      ports :
#          - "8000:8000"
version : "3.3"
services :
  web :
     image: "yashkapadi175/notes-app:latest"
     ports :
         - "127.0.0.1:8000:8000"
